version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db/warehouse
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alembic_migrations
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db/warehouse
    depends_on:
      - db
    entrypoint: ["alembic", "upgrade", "head"]

volumes:
  postgres_data:
